volume (up | sup): key(volup)
volume (down | don | done): key(voldown)
set volume <number>: user.media_set_volume(number)
media mute: key(mute)
media play next: key(next)
media play previous: key(prev)
media (play | stop): user.play_pause()
